version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - docker login -u $dockerhub_username -p $dockerhub_password
      - REPOSITORY_URI=$ecr_uri
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 321177802449.dkr.ecr.us-east-2.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}


  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t spotlight-repo .
      - docker tag spotlight-repo:latest 321177802449.dkr.ecr.us-east-2.amazonaws.com/spotlight-repo:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 321177802449.dkr.ecr.us-east-2.amazonaws.com/spotlight-repo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"'$ecs_container_name'","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
